sudo: false
language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - pypy

env:
  - DJANGO="django==2.0.5"
  - DJANGO="django==1.11.13"
  - DJANGO="django==1.9.8"
  - DJANGO="django==1.8.14"
  
matrix:
  exclude:
    - python: 2.7
      env: DJANGO="django==2.0.5"
    - python: pypy
      env: DJANGO="django==2.0.5"

install:
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pep8
  - pip install https://github.com/un33k/pyflakes/tarball/master
  - pip install coveralls

before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E128 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W finalware; fi

script: coverage run --source=finalware manage.py test

after_success:
  coveralls
